[package]
name = "servicepoint-binding-cs"
version = "0.4.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
servicepoint2 = { path = "../servicepoint2", features = ["c_api", "all_compressions"] }

[build-dependencies]
csbindgen = "1.8.0"
